version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: esyCommerce
      POSTGRES_PASSWORD: esyCommerce
      POSTGRES_DB: esyCommerce
    ports:
      - "5432:5432"
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dhokekiran98@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge
